<a href="https://colab.research.google.com/github/chacha715/ESAA/blob/main/%EC%82%AC%EC%9D%B4%ED%82%B7%EB%9F%B0_%EC%98%88%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **사이킷런으로 시작하는 머신러닝**

**01. 사이킷런 소개와 특징**

*   가급적이면 conda로 셋업(*파이썬 코랩에서는 pip 써야 하는 듯*)
*   version 앞뒤의 '__'는 언더스코어('_')가 연이어 두 개 있는 것

In [ ]:
pip install scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


---
**02. 첫 번째 머신러닝 만들어 보기 - 붓꽃 품종 예측하기**

*   붓꽃의 품종을 분류(Classification). 분류는 대표적인 지도학습 방법의 하나. 지도학습은 학습을 위한 다양한 피처와 분류 결정값인 레이블 데이터로 모델을 학습한 뒤, 별도의 테스트 데이터 세트에서 미지의 레이블을 예측
*   이때 학습을 위해 주어진 데이터 세트를 학습 데이터 세트, 머신러닝 모델의 예측 성능을 평가하기 위해 별도로 주어진 데이터 세트를 테스트 데이터 세트로 지칭

*   꽃잎의 길이와 너비, 꽃받침의 길이와 너비 피처(Feature)를 기반으로 꽃의 품종을 예측하기 위한 것

*   사이킷런 패키지 내의 모듈명은 sklearn으로 시작하는 명명규칙이 있음
*   데이터 세트를 학습 데이터와 테스트 데이터로 분리하는 데는 train_test_split() 함수를 사용. load_iris() 함수를 이용해 붓꽃 데이터 세트를 로딩

*   학습용 데이터와 테스트용 데이터는 반드시 분리해야 함. 이를 위해 사이킷런은 train_test_split() API를 제공. train_test_split()는 호출 시 무작위로 데이터를 분리하므로 random_state를 지정하지 않으면 수행할 때마다 다른 학습/테스트 용 데이터를 만들 수 있음. 숫자 자체는 어떤 값을 지정해도 상관없음
*   train_test_split()은 학습용 피처 데이터 세트를 X_train, 테스트용 피처 데이터 세트를 X_test, 학습용 레이블 데이터 세트를 y_train, 테스트용 레이블 데이터 세트를 y_test로 반환

*   DecisionTreeClassifier를 객체로 생성하여 fit() 메서드에 학습용 피처 데이터 속성과 결정값 데이터 세트를 입력해 호출하면 학습을 수행. 예측은 반드시 학습 데이터가 아닌 다른 데이터를 이용해야 하며, 일반적으로 테스트 데이터 세트를 이용. predict() 메서드에 테스트용 피처 데이터 세트를 입력해 호출하면 예측값 반환
*   정확도는 예측 결과가 실제 레이블 값과 얼마나 정확하게 맞는지를 평가하는 지표. accuracy_score() 함수의 첫 번째 파라미터로 실제 레이블 데이터 세트, 두 번째 파라미터로 예측 레이블 데이터 세트를 입력




In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split 

In [ ]:
import pandas as pd

#붓꽃 데이터 세트를 로딩합니다.
iris=load_iris() 

#iris.data는 Iris 데이터세트에서 feature만으로 된 데이터를 numpy로 가지고 있습니다.
iris_data=iris.data 

#iris.target은 붓꽃 데이터세트에서 레이블(결정값) 데이터를 numpy로 가지고 있습니다.
iris_label=iris.target
print('iris target값:', iris_label)
print('iris target명: ', iris.target_names)

#붓꽃 데이터 세트를 자세히 보기 위해 DataFrame으로 변환합니다.
iris_df=pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df.head(3)

iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명:  ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [ ]:
X_train, X_test, y_train, y_test=train_test_split(iris_data,iris_label, 
                                                  test_size=0.2, random_state=11)

In [ ]:
#DecisionTreeClassifier 객체 생성
dt_clf=DecisionTreeClassifier(random_state=11)

In [ ]:
#학습 수행
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

In [ ]:
#학습이 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행
pred=dt_clf.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도: 0.9333


---
**03. 사이킷런의 기반 프레임워크 익히기**

*   **Estimator 이해 및 fit(), predict() 메서드**
 *   사이킷런에서는 분류 알고리즘을 구현한 클래스를 Classifier로, 그리고 회귀 알고리즘을 구현한 클래스를 Regressor로 지칭. 이를 합쳐서 Estimator 클래스. Estimator 클래스는 fit()과 predict()를 내부에서 구현
  *   사이킷런에서 비지도학습인 차원 축소, 클러스터링, 피처 추출 등을 구현한 클래스 역시 대부분 fit()과 transform()을 적용. 비지도학습과 피처 추출에서 fit()은 입력 데이터의 형태에 맞춰 데이터를 변환하기 위한 사전 구조를 맞추는 작업. fit()으로 변환을 위한 사전 구조를 맞추면 이후 입력 데이터의 차원 변화, 클러스터링, 피처 추출 등의 실제 작업은 transform()으로 수행. 이를 하나로 결합한 fit_transform()도 제공하지만, 사용에 약간의 주의가 필요

*   **사이킷런의 주요 모듈**
 *   일반적으로 머신러닝 모델을 구축하는 주요 프로세스는 피처의 가공, 변경, 추출을 수행하는 피처 처리, ML 알고리즘 학습/예측 수행, 그리고 모델 평가의 단계를 반복적으로 수행하는 것

*   **내장된 예제 데이터 세트**
 *   사이킷런에 내장되어 있는 데이터 세트는 분류나 회귀를 연습하기 위한 예제용도의 데이터 세트와 분류나 클러스터링을 위해 표본 데이터로 생성될 수 있는 데이터 세트로 나뉘어짐.
  *   fetch 계열의 명령은 데이터 크기가 커서 패키지에 처음부터 저장돼 있지 않고 인터넷에서 내려받아 scikit_learn_data라는 서브 디렉터리에 저장한 후 추후 불러들이는 데이터. 최초 사용 시에 인터넷에 연결돼 있어야 함
  *   사이킷런에 내장된 데이터 세트는 일반적으로 딕셔너리 형태
  *   data, target은 넘파이 배열(ndarray) 타입이며, target_names, feature_names는 넘파이 배열 또는 파이썬 리스트(list) 타입입니다. DESCR은 스트링 타입입니다. 피처의 데이터 값을 반환받기 위해서는 내장 데이터 세트 API를 호출한 뒤에 그 Key 값을 지정하면 됨




In [ ]:
from sklearn.datasets import load_iris

iris_data=load_iris()
print(type(iris_data))

<class 'sklearn.utils.Bunch'>


In [ ]:
keys = iris_data.keys()
print('붓꽃데이터 세트의 키들: ', keys)

붓꽃데이터 세트의 키들:  dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [ ]:
print('\n feautre names의 type: ', type(iris_data.feature_names))
print('feautre names의 shape: ', len(iris_data.feature_names))
print(iris_data.feature_names)

print('\n target_names의 type: ', type(iris_data.target_names))
print('target_names의 shape: ', len(iris_data.feature_names))
print(iris_data.target_names)

print('\n data의 type: ', type(iris_data.data))
print('data의 shape: ', len(iris_data.data.shape))
print(iris_data['data'])

print('\n target의 type: ', type(iris_data.target))
print('target의 shape: ', len(iris_data.target.shape))
print(iris_data.target)


 feautre names의 type:  <class 'list'>
feautre names의 shape:  4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names의 type:  <class 'numpy.ndarray'>
target_names의 shape:  4
['setosa' 'versicolor' 'virginica']

 data의 type:  <class 'numpy.ndarray'>
data의 shape:  2
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3

---
**04. Model Selection 모듈 소개**

*   **학습/테스트 데이터 세트 분리 - train_test_split()**
 *   예측을 수행하는 데이터 세트는 학습을 수행한 학습용 데이터 세트가 아닌 전용의 테스트 데이터 세트여야 함

*   **교차 검증**
 *   앞선 방법은 모델이 학습 데이터에만 과도하게 최적화되어, 실제 예측을 다른 데이터로 수행할 경우에는 예측 성능이 과도하게 떨어지는 과적합(Overfitting)에 취약함. 교차검증은 데이터 편중을 막기 위해 별도의 여러 세트로 구성된 학습 데이터 세트와 검증 데이터 세트에서 학습과 평가를 수행하는 것. ML에 사용되는 데이터 세트를 세분화해서 학습, 검증, 테스트 데이터 세트로 나눌 수 있음. 테스트 데이터 세트 외에 별도의 검증 데이터 세트를 둬서 최종 평가 이전에 학습된 모델을 다양하게 평가하는 데 사용

 *   K폴드 교차 검증: K개의 데이터 폴드 세트를 만들어서 K번만큼 각 폴드 세트에 학습과 검증 평가를 반복적으로 수행. 그 후, 이 5개의 평가를 평균한 결과를 가지고 예측 성능을 평가. 사이킷런에서는 K폴드 교차 검증 프로세스를 구현하기 위해 KFold와 StratifiedKFold 클래스를 제공
 *   Stratified K 폴드: 불균형한 분포도를 가진 레이블 데이터 집합을 위한 K 폴드 방식. 레이블 값으로 1이 특정 개별 반복별 학습/테스트 데이터 세트에는 상대적으로 많이 들어 있고, 다른 반복 학습/테스트 데이터 세트에는 그렇지 못한 결과가 발생할 수 있기에 원본 데이터와 유사한 레이블 값의 분포를 학습/테스트 세트에도 유지하는 게 매우 중요. 사용법에서 위와 큰 차이는 StratifiedKFold는 레이블 데이터 분포도에 따라 학습/검증 데이터를 나누기 때문에 split() 메서드에 인자로 피처 데이터 세트뿐만 아니라 레이블 데이터 세트도 반드시 필요하다는 것
 *   교차 검증을 보다 간편하게 - cross_val_score(): 비슷한 API로 cross_validate() 존재. cross_val_score()는 단 하나의 평가 지표만 가능하지만, cross_validate()는 여러 개의 평가 지표 반환 가능. 또한 학습 데이터에 대한 성능 평가 지표와 수행 시간도 같이 제공

*   **GridSearchCV - 교차 검증과 최적 하이퍼 파라미터 튜닝을 한 번에**
 *   하이퍼 파라미터는 머신러닝 알고리즘을 구성하는 주요 구성 요소이며, 이 값을 조정해 알고리즘의 예측 성능을 개선할 수 있음. 데이터 세트를 cross-validation을 위한 학습/테스트 세트로 자동으로 분할한 뒤에 하이퍼 파라미터 그리드에 기술된 모든 파라미터를 순차적으로 적용해 최적의 파라미터를 찾도록 함. 수행시간이 상대적으로 오래 걸림

In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris=load_iris()
dt_clf=DecisionTreeClassifier()
train_data=iris.data
train_label=iris.target
dt_clf.fit(train_data, train_label)

#학습데이터 세트로 예측 수행
pred=dt_clf.predict(train_data)
print('예측정확도:', accuracy_score(train_label, pred))

예측정확도: 1.0


In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris=load_iris()
features=iris.data
label=iris.target
dt_clf=DecisionTreeClassifier(random_state=156)

#5개의폴드세트로분리하는 KFold 객체와 폴드세트별 정확도를 담을 리스트 객체 생성
kfold=KFold(n_splits=5)
cv_accuracy=[]
print('붓꽃 데이터 세트 크기:', features.shape[0])

붓꽃 데이터 세트 크기: 150


In [ ]:
n_iter=0

#KFold 객체의 split()를 호출 시 폴드 별 학습용,검증용 테스트의 로우 인덱스를 array로 반환
for train_index, test_index in kfold.split(features):
  #Kfold.split()으로 반환된 인덱스를 이용해 학습용 검증용 테스트 데이터 추출
  X_train, X_test=features[train_index],features[test_index]
  y_train,y_test=label[train_index],label[test_index]
  #학습 및 예측
  dt_clf.fit(X_train, y_train)
  pred=dt_clf.predict(X_test)
  n_iter+=1
  #반복 시 마다 정확도 측정
  accuracy=np.round(accuracy_score(y_test, pred),4)
  train_size=X_train.shape[0]
  test_size=X_test.shape[0]
  print('\n#{0} 교차검증정확도 :{1}, 학습데이터크기: {2}, 검증데이터크기: {3}'.format(n_iter, accuracy, train_size,test_size))
  print('#{0} 검증세트인덱스 :{1}'.format(n_iter, test_index))
  cv_accuracy.append(accuracy)

#개별 iteration별 정확도를 합하여 평균 정확도 계산
print('\n## 평균검증정확도: ', np.mean(cv_accuracy))


#1 교차검증정확도 :1.0, 학습데이터크기: 120, 검증데이터크기: 30
#1 검증세트인덱스 :[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차검증정확도 :0.9667, 학습데이터크기: 120, 검증데이터크기: 30
#2 검증세트인덱스 :[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차검증정확도 :0.8667, 학습데이터크기: 120, 검증데이터크기: 30
#3 검증세트인덱스 :[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차검증정확도 :0.9333, 학습데이터크기: 120, 검증데이터크기: 30
#4 검증세트인덱스 :[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차검증정확도 :0.7333, 학습데이터크기: 120, 검증데이터크기: 30
#5 검증세트인덱스 :[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균검증정확도:  0.9


In [ ]:
import pandas as pd

iris=load_iris()
iris_df=pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [ ]:
kfold=KFold(n_splits=3)
n_iter=0
for train_index, test_index in kfold.split(iris_df):
  n_iter+=1
  label_train=iris_df['label'].iloc[train_index]
  label_test=iris_df['label'].iloc[test_index]
  print('##교차검증: {0}'.format(n_iter))
  print('학습 레이블 데이터 분포: \n', label_train.value_counts())
  print('검증 레이블 데이터 분포: \n', label_test.value_counts())

##교차검증: 1
학습 레이블 데이터 분포: 
 1    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 0    50
Name: label, dtype: int64
##교차검증: 2
학습 레이블 데이터 분포: 
 0    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 1    50
Name: label, dtype: int64
##교차검증: 3
학습 레이블 데이터 분포: 
 0    50
1    50
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 2    50
Name: label, dtype: int64


In [ ]:
from sklearn.model_selection import StratifiedKFold

skf=StratifiedKFold(n_splits=3)
n_iter=0

for train_index, test_index in skf.split(iris_df, iris_df['label']):
  n_iter+=1
  label_train=iris_df['label'].iloc[train_index]
  label_test=iris_df['label'].iloc[test_index]
  print('##교차검증: {0}'.format(n_iter))
  print('학습 레이블 데이터 분포: \n', label_train.value_counts())
  print('검증 레이블 데이터 분포: \n', label_test.value_counts())

##교차검증: 1
학습 레이블 데이터 분포: 
 2    34
0    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 0    17
1    17
2    16
Name: label, dtype: int64
##교차검증: 2
학습 레이블 데이터 분포: 
 1    34
0    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 0    17
2    17
1    16
Name: label, dtype: int64
##교차검증: 3
학습 레이블 데이터 분포: 
 0    34
1    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 1    17
2    17
0    16
Name: label, dtype: int64


In [ ]:
dt_clf=DecisionTreeClassifier(random_state=156)

skfold=StratifiedKFold(n_splits=3)
n_iter=0
cv_accuracy=[]

#StratifiedKFold의 split()호출 시 반드시 레이블 데이터 세트도 추가입력 필요
for train_index, test_index in skfold.split(features, label):
  #split()으로 반환된 인덱스를 이용해 학습용 검증용 테스트 데이터 추출
  X_train, X_test=features[train_index],features[test_index]
  y_train, y_test=label[train_index],label[test_index]
  #학습 및 예측
  dt_clf.fit(X_train, y_train)
  pred=dt_clf.predict(X_test)

  #반복 시 마다 정확도 측정
  n_iter+=1
  accuracy=np.round(accuracy_score(y_test, pred),4)
  train_size=X_train.shape[0]
  test_size=X_test.shape[0]
  print('\n#{0} 교차검증정확도 :{1}, 학습데이터크기: {2}, 검증데이터크기: {3}'.format(n_iter, accuracy, train_size,test_size))
  print('#{0} 검증세트인덱스 :{1}'.format(n_iter, test_index))
  cv_accuracy.append(accuracy)

#교차검증별 정확도 및 평균 정확도 
print('\n## 교차검증별 정확도: ', np.round(cv_accuracy, 4))
print('\n## 평균검증정확도: ', np.mean(cv_accuracy))


#1 교차검증정확도 :0.98, 학습데이터크기: 100, 검증데이터크기: 50
#1 검증세트인덱스 :[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

#2 교차검증정확도 :0.94, 학습데이터크기: 100, 검증데이터크기: 50
#2 검증세트인덱스 :[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

#3 교차검증정확도 :0.98, 학습데이터크기: 100, 검증데이터크기: 50
#3 검증세트인덱스 :[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## 교차검증별 정확도:  [0.98 0.94 0.98]

## 평균검증정확도:  0.9666666666666667


In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

iris_data=load_iris()
df_clf=DecisionTreeClassifier(random_state=156)

data=iris_data.data
label=iris_data.target

#성능지표는 정확도(accuracy), 교차 검증 세트는 3개
scores=cross_val_score(df_clf, data, label,scoring='accuracy', cv=3)
print(' 교차 검증별 정확도: ', np.round(scores, 4))
print('평균 검증 정확도: ', np.round(np.mean(scores),4))

 교차 검증별 정확도:  [0.98 0.94 0.98]
평균 검증 정확도:  0.9667


In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
import numpy as np

iris=load_iris()
X_train, X_test, y_train, y_tesdt=train_test_split(iris_data.data, iris_data.target, test_size=0.2, random_state=121)

dtree=DecisionTreeClassifier()

###파라미터를 딕셔너리 형태로 설정
parameters={'max_depth':[1,2,3],'min_samples_split':[2,3]}

In [ ]:
import pandas as pd
from sklearn.model_selection import GridSearchCV

grid_dtree=GridSearchCV(dtree,param_grid=parameters,cv=3,refit=True)
grid_dtree.fit(X_train,y_train)

#GridSearchCV 결과 추출하여 DataFRame 변환
scores_df=pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params','mean_test_score','rank_test_score','split0_test_score','split1_test_score', 'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [ ]:
print('gridserachCV 최적파라미터: ', grid_dtree.best_params_)
print('gridserachCV 최고 정확도: {0:.4f}'.format(grid_dtree.best_score_))

gridserachCV 최적파라미터:  {'max_depth': 3, 'min_samples_split': 2}
gridserachCV 최고 정확도: 0.9750


---
**05. 데이터 전처리**

 *   결손값, 즉 NaN, Null 값은 고정된 다른 값으로 변환해야 함. Null 값이 얼마 되지 않는다면 피처의 평균값 등으로 대체 가능, Null 값이 대부분이라면 해당 피처는 드롭하는 것이 더 좋음
 *   사이킷런의 머신러닝 알고리즘은 무자열 값을 입력 값으로 허용하지 않음. 모든 무자열 값은 인코딩돼서 숫자 형으로 변화해야 함. 문자열 피처는 일반적으로 카테고리형 피처와 텍스트형 피처를 의미

*   **데이터 인코딩**
 *   레이블 인코딩: 카테고리 피처를 코드형 숫자 값으로 변환하는 것. LabelEnconder 클래스로 구현. 문자열 값이 어떤 숫자 값으로 인코딩됐는지는 LabelEncoder 객체의 classes_속성값으로 확인. classes_속성은 0번부터 순서대로 변환된 인코딩 값에 대한 원본값을 가짐. inverse_transform()을 통해 인코딩된 값을 다시 디코딩 가능. 레이블 인코딩이 일괄적인 숫자 값으로 변환되면서 선형 회귀와 같은 몇몇 ML 알고리즘에는 예측 성능이 떨어지는 경우가 발생-숫자 값의 경우 크고 작음에 대한 특성이 작용하기 때문
 *   원-핫 인코딩: 피처 값의 유형에 따라 새로운 피처를 추가해 고유 값에 해당하는 칼럼에만 1을 표시하고 나머지 칼럼에는 0을 표시. 사이킷런에서 OneHotEncoder 클래스로 쉽게 변환 가능. 주의할 점은, OneHotEncoder로 변환하기 전에 모든 문자열 값이 숫자형 값으로 변환돼야 하고, 입력 값으로 2차원 데이터가 필요하다는 점. 판다스 API로 get_dummies() 이용 시 사이킷런의 OneHotEncoder와 다르게 문자열 카테고리 값을 숫자 형으로 변환할 필요 없이 바로 변환 가능

*   **피처 스케일링과 정규화**
 *   서로 다른 변수의 값 범위를 일정한 수준으로 맞추는 작업을 피처 스케일링. 대표적인 방법으로 표준화와 정규화.
 *   표준화는 데이터의 피처 각각이 평균이 0이고 분산이 1인 가우시안 정규 분포를 가진 값으로 변환하는 것
 *   정규화는 서로 다른 피러의 크기를 모두 똑같은 단위로 변경하는 것
 *   사이킷런 전처리에서 제공하는 Normalizer 모듈과 일반적인 정규화는 약간의 차이. 사이킷런에서는 선형대수에서의 정규화 개념이 적용되어 개별 벡터의 크기를 맞추기 위해 변화하는 것을 의미

*   **StandardScaler**
 *  앞에서 설명한 표준화를 쉽게 지원하기 위한 클래스
*   **MinmaxScaler**
 *   데이터값을 0과 1사이의 범위값으로 변환(음수 값이 있으면 -1에서 1값으로 변환)
*   **학습 데이터와 테스트 데이터의 스케일링 변환 시 유의점**
 *   학습 데이터로 fit()이 적용된 기준 정보를 그대로 테스트 데이터에 적용해야 하며, 그렇지 않고 테스트 데이터로 다시 새로운 스케일링 기준 정보를 만들게 되면 학습 데이터와 테스트 데이터의 스케일링 기준 정보가 달리지므로 올바른 예측 결과를 도출하지 못할 수 있음. 반드시 테스트 데이터는 학습 데이터의 스케일링 기준에 따라야 함. 그러므로 학습과 테스트 데이터 세트로 분리하기 전에 전체 데이터 세트에 스케일링을 적용한 뒤 학습과 테스트 데이터 세트로 분리하는 것이 바람직



In [ ]:
from sklearn.preprocessing import LabelEncoder

items=['TV','냉장고','전자레인지','컴퓨터', '선풍기','선풍기','믹서','믹서']

#LabelsEncoder를 객체로 생성 후, fit()과 Transform()으로 레이블 인코딩 수행
encoder=LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)
print('인코딩변환값: ',labels)

인코딩변환값:  [0 1 4 5 3 3 2 2]


In [ ]:
print('인코딩클래스: ',encoder.classes_)

인코딩클래스:  ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [ ]:
print('디코딩원본값: ',encoder.inverse_transform([4,5,2,0,1,1,3,3]))

디코딩원본값:  ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['TV','냉장고','전자레인지','컴퓨터', '선풍기','선풍기','믹서','믹서']

#먼저 숫자값 반환을 위해 LabelsEncoder로 변환

encoder=LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)
#2차원데이터변환
labels=labels.reshape(-1, 1)

#원핫인코딩 적용 
oh_encoder=OneHotEncoder()
oh_encoder.fit(labels)
oh_labels=oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 차원
(8, 6)


In [ ]:
import pandas as pd
df=pd.DataFrame({'item':['TV','냉장고', '전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

In [ ]:
from sklearn.datasets import load_iris
import pandas as pd
#붓꽃데이터세트로딩, Dataframe으로변환
iris=load_iris()
iris_data=iris.data
iris_df=pd.DataFrame(data=iris_data, columns=iris.feature_names)

print('feature들의 평균값')
print(iris_df.mean())
print('\nfeature들의 분산값')
print(iris_df.var())

feature들의 평균값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature들의 분산값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [ ]:
from sklearn.preprocessing import StandardScaler

#StandardScaler 객체생성
scaler=StandardScaler()
#StandardScaler로데이터세트변환. fit()과 transform()호출
scaler.fit(iris_df)
iris_scaled=scaler.transform(iris_df)

#transform()시 스케일변환된 데이터세트가 numpy ndarray로 반환돼 이를 DataFrame 변환
iris_df_sclaed=pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature들의 평균값')
print(iris_df.mean())
print('\nfeature들의 분산값')
print(iris_df.var())

feature들의 평균값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature들의 분산값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()
scaler.fit(iris_data)
iris_scaled=scaler.transform(iris_df)

#transform()시 스케일 변환된 데이터 세트가 NumPy ndarray로 반환돼 이를 Dataframe으로 변환
iris_df_scaled=pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature들의 최솟값')
print(iris_df_scaled.min())
print('\nfeature들의 최댓값')
print(iris_df_scaled.max())

feature들의 최솟값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature들의 최댓값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"


In [ ]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

train_array=np.arange(0,11).reshape(-1, 1)
test_array=np.arange(0,6).reshape(-1, 1)

In [ ]:
scaler=MinMaxScaler()

scaler.fit(train_array)

train_scaled=scaler.transform(train_array)

print('원본 train_array',np.round(train_array.reshape(-1),2))
print('Scaled train_array',np.round(train_scaled.reshape(-1),2))

원본 train_array [ 0  1  2  3  4  5  6  7  8  9 10]
Scaled train_array [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [ ]:
scaler.fit(test_array)

test_scaled=scaler.transform(test_array)

print('원본 test_array',np.round(test_array.reshape(-1),2))
print('Scaled test_array',np.round(test_scaled.reshape(-1),2))

원본 test_array [0 1 2 3 4 5]
Scaled test_array [0.  0.2 0.4 0.6 0.8 1. ]


In [ ]:
scaler=MinMaxScaler()
scaler.fit(train_array)
train_scaled=scaler.transform(train_array)
print('원본 train_array 데이터', np.round(train_array.reshape(-1),2))
print('Scaled train_array',np.round(train_scaled.reshape(-1),2))

#test_array에 Scale 변환시반드시 transform()
test_scaled=scaler.transform(test_array)
print('\n원본 test_array',np.round(test_array.reshape(-1),2))
print('Scaled test_array',np.round(test_scaled.reshape(-1),2))

원본 train_array 데이터 [ 0  1  2  3  4  5  6  7  8  9 10]
Scaled train_array [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

원본 test_array [0 1 2 3 4 5]
Scaled test_array [0.  0.1 0.2 0.3 0.4 0.5]
